name: CxFlow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: CHECKMARX
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Run CxFlow Scan
      run: |
          java -jar "C:\Cx-Flow\Jar\cx-flow.1.7.08.jar" \
            --scan \
            --repo-url=https://github.com/${{ github.repository }} \
            --rep-name=${{ github.event.repository.name }} \
            --branch=${{ github.ref_name }} \
            --namespace=${{ github.repository_owner }} \
            --project-name=${{ github.repository }}-PR \
            --bug-tracker=WAIT \
            --sca.appUrl=${{ secrets.SCA_API_URL }} \
            --sca.apiUrl=${{ secrets.SCA_APP_URL }} \
            --sca.accessControlUrl=${{ secrets.SCA_ACCESS_CONTROL_URL }} \
            --sca.tenant=${{  secrets.SCA_TENANT }} \
            --sca.username=${{ secrets.SCA_USERNAME }} \
            --sca.password=${{ secrets.SCA_PASSWORD }} \
            --logging.level.com.checkmarx.*=DEBUG
