name: CxFlow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: CHECKMARX
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Get CxFLow
      run: |
           wget -O ./cx-flow.jar "https://github.com/checkmarx-ltd/cx-flow/releases/download/1.7.08/cx-flow-1.7.08.jar"
        
    - name: Run CxFlow Scan
      run: |
        java -jar cx-flow-1.7.08.jar --scan --github --repo-url=https://github.com/${{ github.repository }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --namespace=${{ github.repository_owner }} --cx-project=${{ github.event.repository.name }} --bug-tracker=WAIT --sca.appUrl=${{ secrets.SCA_APP_URL }} --sca.apiUrl=${{ secrets.SCA_API_URL }} --sca.accessControlUrl=${{ secrets.SCA_ACCESS_CONTROL_URL }} --sca.tenant=${{  secrets.SCA_TENANT }} --sca.username=${{ secrets.SCA_USERNAME }} --sca.password=${{ secrets.SCA_PASSWORD }} --cxflow.enabled-vulnerability-scanners="sca" --logging.level.com.checkmarx.*=DEBUG
