name: CxFlow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '39 15 * * 1'

permissions:
  contents: read

jobs:
  build:
    name: CHECKMARX
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Checkmarx CxFlow Action
      env:
        #SCA_SCARESOLVERADDPARAMETERS_CUSTOM-PARAMETER : "--gradle-parameters=-Paws.codeartifact.username=${{ github.repository_owner }} -Paws.codeartifact.token=${{ github.repository_owner }}"
        #SCA_SCARESOLVERADDPARAMETERS_LOG-LEVEL : Debug
        #JIRA_FIELDS_0_JIRA_DEFAULT_VALUE : APPSEC-2371
        #JIRA_FIELDS_0_JIRA_FIELD_NAME : "Epic Link"
        #JIRA_FIELDS_0_JIRA_FIELD_TYPE : text
        #JIRA_FIELDS_0_TYPE : static
        #CXFLOW_VERSION : github_action
        CHECKMARX_BASE_URL : ${{ secrets.CHECKMARX_URL }}
        CHECKMARX_PASSWORD : ${{ secrets.CHECKMARX_PASSWORD }}
        CHECKMARX_USERNAME : ${{ secrets.CHECKMARX_USERNAME }}
        CHECKMARX_TEAM : ${{ secrets.CHECKMARX_TEAMS }}
        CHECKMARX_CLIENT_SECERT :  ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        CXFLOW_ENABLED_VULNERABILITY_SCANNERS : SAST
        CXFLOW_BUGTRACKER : WAIT
      run: docker run --entrypoint ./entrypoint.sh -e CHECKMARX_BASE_URL -e CHECKMARX_PASSWORD -e CHECKMARX_USERNAME -e CHECKMARX_TEAM -e CHECKMARX_CLIENT_SECERT -e CXFLOW_ENABLED_VULNERABILITY_SCANNERS -e CXFLOW_BUGTRACKER itskedar/mycxflow:github_action --scan --SHA=$GITHUB_SHA  --github.api-url="${GITHUB_API_URL}/repos/" --cx-project="${{ github.repository }}-PR" --f=. --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.*=DEBUG 

      
