name: CxFlow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: CHECKMARX
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
        
    - name: Checkmarx CxFlow Action
      uses: CxDrake/checkmarx-cxflow-github-action@01153b658f969264711f747697ab809c4f3f1a82
      env:
        CXFLOW_PROJECTCUSTOMFIELD : "git:git test,kedar:bhujade,test:test1"
      with:
        project: ${{ github.repository }}-PR
        team: ${{ secrets.CHECKMARX_TEAMS }}
        checkmarx_url: ${{ secrets.CHECKMARX_URL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        scanners: sast
        incremental: false
        #extra_certificates: .
        break_build: true
        preset: 'Checkmarx Default'
        bug_tracker: GitHub
        sca_api_url: ${{ secrets.SCA_API_URL }}
        sca_app_url: ${{ secrets.SCA_APP_URL }}
        sca_access_control_url: ${{ secrets.SCA_ACCESS_CONTROL_URL }}
        sca_tenant: ${{  secrets.SCA_TENANT }}
        sca_username: ${{ secrets.SCA_USERNAME }}
        sca_password: ${{ secrets.SCA_PASSWORD }}
        jira_url : 'https://kedarbhujade.atlassian.net'
        jira_username : 'kedar.bhujade6@gmail.com'
        jira_token : ${{ secrets.JIRA_TOKEN }}
        jira_project : 'APPSEC'
        jira_issue_type : 'Bug'
        jira_open_transition : 'In Progress'
        jira_close_transition : 'Done'
        jira_open_status : 'Selected for Development,In Progress'
        jira_closed_status : 'Done'
        params: '--checkmarx.cx-branch=true --checkmarx.settings-override=true --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --merge-id=${{ github.event.number }} --logging.level.com.checkmarx.*=DEBUG'
